FROM openjdk:11.0.11-jdk as builder
#FROM ssq/iac/java-ssq:corretto-11-latest
WORKDIR source
ARG JAR_FILE=/target/SpringBootLovesK8sApplication-*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM openjdk:11.0.11-jre
WORKDIR application
COPY --from=builder source/dependencies/ ./
COPY --from=builder source/spring-boot-loader/ ./
COPY --from=builder source/snapshot-dependencies/ ./
COPY --from=builder source/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]